// Generated by Wrangler
// Running `bun run types` will update this file

interface Env {
  DB: D1Database;
  SESSION: KVNamespace;
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  DISCORD_GUILD_ID: string;
  OWNER_DISCORD_ID: string;
  MAINTAINER_ROLE_IDS: string;
  MIN_ACCOUNT_AGE_DAYS: string;
  PUBLIC_SITE_NAME: string;
}
